using CSV
using DataFrames
using Distributions
using Random

# Starter table for "Your own data": pond surveys. SIMULATED data, not real counts, generated by
# this seeded script (seed = STARTER_PONDS_SEED, MersenneTwister). Regenerate with:
#   julia --project=. data/starter_ponds.jl
# which overwrites data/starter_ponds.csv next to this file.
#
# Columns:
#   pond       - a code, P01 to P60
#   site       - "north" or "south"
#   treatment  - "shaded" or "open"
#   water_temp - water temperature, degrees C, 1 decimal. Exactly two values are left empty
#                on purpose, so learners meet a missing value in a safe place.
#   frogs      - frogs counted at the pond (Poisson draw). Shaded ponds are a little cooler
#                and have somewhat more frogs.

const STARTER_PONDS_SEED = 20261002
const N_PONDS = 60
const N_MISSING = 2

function simulate_starter_ponds(seed::Integer = STARTER_PONDS_SEED)
    rng = MersenneTwister(seed)
    pond = String[]
    site = String[]
    treatment = String[]
    water_temp = Union{Missing,Float64}[]
    frogs = Int[]
    for i in 1:N_PONDS
        s = i <= N_PONDS ÷ 2 ? "north" : "south"
        tr = isodd(i) ? "shaded" : "open"
        t = round(18.5 - (tr == "shaded" ? 2.0 : 0.0) + 2.0 * randn(rng), digits = 1)
        rate = 8.0 * (tr == "shaded" ? 1.4 : 1.0) * (s == "north" ? 1.1 : 1.0)
        push!(pond, "P" * lpad(i, 2, '0'))
        push!(site, s)
        push!(treatment, tr)
        push!(water_temp, t)
        push!(frogs, rand(rng, Poisson(rate)))
    end
    for i in randperm(rng, N_PONDS)[1:N_MISSING]
        water_temp[i] = missing
    end
    DataFrame(pond = pond, site = site, treatment = treatment, water_temp = water_temp, frogs = frogs)
end

if abspath(PROGRAM_FILE) == @__FILE__
    df = simulate_starter_ponds()
    path = joinpath(@__DIR__, "starter_ponds.csv")
    CSV.write(path, df)
    println("wrote $(nrow(df)) rows to $path")
end
