using CSV
using DataFrames
using Distributions
using Random

# Toto's water fleas (Daphnia). SIMULATED data — not real counts — generated by this seeded
# script (seed = WATER_FLEAS_SEED, MersenneTwister). Regenerate with:
#   julia --project=. data/water_fleas.jl
# which overwrites data/water_fleas.csv next to this file.
#
# Columns:
#   pond  — one of "north", "south", "east", "west"
#   jar   — jar number within a pond, 1..12
#   count — Daphnia counted in that jar (Poisson draw; pond mean differs on the log scale,
#           with a mild positive effect of water temperature)
#   temp  — water temperature in that jar, degrees C (roughly 14-24, rounded to 1 decimal)

const WATER_FLEAS_SEED = 20260928

const PONDS = ["north", "south", "east", "west"]
const JARS_PER_POND = 12

# Baseline Daphnia rate per pond (Poisson mean at temp = 19C), on the log scale so pond
# differences are multiplicative. North highest, west lowest, well separated.
const POND_LOG_RATE = Dict(
    "north" => log(38.0),
    "south" => log(24.0),
    "east" => log(14.0),
    "west" => log(7.0),
)

const TEMP_EFFECT = 0.025  # mild positive effect of temperature on log(count rate)

function simulate_water_fleas(seed::Integer = WATER_FLEAS_SEED)
    rng = MersenneTwister(seed)
    pond = String[]
    jar = Int[]
    count = Int[]
    temp = Float64[]
    for p in PONDS
        for j in 1:JARS_PER_POND
            t = round(14.0 + 10.0 * rand(rng), digits = 1)
            log_rate = POND_LOG_RATE[p] + TEMP_EFFECT * (t - 19.0)
            c = rand(rng, Poisson(exp(log_rate)))
            push!(pond, p)
            push!(jar, j)
            push!(count, c)
            push!(temp, t)
        end
    end
    DataFrame(pond = pond, jar = jar, count = count, temp = temp)
end

if abspath(PROGRAM_FILE) == @__FILE__
    df = simulate_water_fleas()
    path = joinpath(@__DIR__, "water_fleas.csv")
    CSV.write(path, df)
    println("wrote $(nrow(df)) rows to $path")
end
